#!/usr/bin/env python
# Nginx Admin Installer
# Website: www.nginxcp.com
#
# Copyright (C) NGINXCP.COM.
#
# Hook to run on parked domain (alias) create/remove
#
import subprocess
import sys
import os
import yaml
import json
from xml.dom import minidom
sys.path.append('/usr/local/cpanel/scripts')
import createvhosts
import xmlapi

inputdoc = minidom.parse(sys.stdin)

ipDOC = xmlapi.api("listips")
parsedipDOC = json.loads(ipDOC)
ips = parsedipDOC.get('result')
iplist = []

for ip in ips:
    iplist.append(ip.get('ip'))

resulttaglist = inputdoc.getElementsByTagName('result')
resultlist = []
newdomaintaglist = inputdoc.getElementsByTagName('param0')
domain = newdomaintaglist[0].childNodes[0].toxml()
usertaglist = inputdoc.getElementsByTagName('USER')
user = usertaglist[0].childNodes[0].toxml()

DOC = xmlapi.api("accountsummary?user=" + user)
parsedDOC = json.loads(DOC)
acct = parsedDOC.get('acct')[0]
domain = acct.get('domain')
docroot, yip, alias = createvhosts.getvars(domain)
acct_ip = acct.get('ip')
if acct_ip == iplist[0]:
    createvhosts.writeconfshared(user, domain, docroot, yip, alias)
else:
    createvhosts.writeconfded(user, domain, docroot, yip, alias)

scriptname = os.path.basename(sys.argv[0])
if scriptname == 'park':
    proc = subprocess.Popen("/etc/init.d/nginx restart > /dev/null 2>&1", shell=True)
